name: Kover diff coverage
on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Generate Kover Report
        run: |
          ./gradlew koverXmlReport
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff

      - name: Compute Diff Coverage
        uses: mi-kas/kover-report@v1
        with:
          path: build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-changed-files: 80
          coverage-counter-type: LINE