name: Kover diff coverage
on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Kover Report
        run: |
          ./gradlew koverXmlReport
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff

      - name: Compute Diff Coverage
        uses: mi-kas/kover-report@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}/composeApp/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-changed-files: 80
          coverage-counter-type: LINE