name: Kover diff coverage
on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Kover Report
        run: |
          ./gradlew koverXmlReport
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff

      - name: Compute Diff Coverage
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/coach/composeApp/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-changed-files: 80
          coverage-counter-type: LINE