name: scan diff with ktlint
on: [pull_request]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: ktlint
        run: |
          ./gradlew ktlintCheck