name: Run pull request checks

on:
  pull_request:
    branches:
      - main
      -
jobs:
  ktlint:
    uses: ./.github/workflows/ktlint.yml

  codeCoverage:
    uses: ./.github/workflows/codeCoverage.yml

  workflow3:
    needs: codeCoverage
    uses: ./.github/workflows/unitTests.yml