name: Run unit tests

on: workflow_call

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run ktlint
        run: |
          ./gradlew test